---
# This file takes all the required hyperparameters

VECTOR_DB_DISEASE_ENTITY_PATH : '../data/disease_with_relation_to_genes.pickle'
VECTOR_DB_PATH : '../data/vectorDB/disease_nodes_db'
VECTOR_DB_CHUNK_SIZE : 650
VECTOR_DB_CHUNK_OVERLAP : 200
VECTOR_DB_BATCH_SIZE : 200
VECTOR_DB_SENTENCE_EMBEDDING_MODEL : 'sentence-transformers/all-MiniLM-L6-v2'

# Just note that, this assumes you GPT config file is in the $HOME path, if not, change it accordingly
GPT_CONFIG_FILE : '$HOME/.gpt_config.env'
GPT_API_TYPE : 'azure'